version: '3.9'
services:
  app:
    container_name: trading-ai
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      N8N_URL: http://n8n:5678
      REDIS_URL: redis://redis-stack-server:6379
    depends_on:
      - redis-stack-server
    restart: unless-stopped

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Europe/Kyiv"
      TZ: "Europe/Kyiv"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  n8n_data:
  redis-data:
